version: "3"
services:
  api:
    container_name: wish-list-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGO_HOST: 'mongo'
        MONGO_PORT: 27017
        MONGO_DBNAME: 'kts'

    ports:
      - "8080:8080"

    environment:
      MONGO_HOST: 'mongo'
      MONGO_PORT: 27017
      MONGO_DBNAME: 'kts'

    depends_on:
      - mongo

  mongo:
    container_name: wish-list-mongo
    image: mongo:4
    restart: always
    ports:
      - "27017"

  # elasticsearch:
  #   container_name: wish-list-elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
