swagger: "2.0"
info:
  description: "Это документация к API сервиса  Lets party"
  version: "1.0.0"
  title: "Lets party service"
  # termsOfService: "http://swagger.io/terms/"
  # contact:
  #   email: "apiteam@swagger.io"
  # license:
  #   name: "Apache 2.0"
  #   url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: "petstore.swagger.io"
# basePath: "/v2"
tags:
- name: "events"
  description: "Все, что связано с событиями"
  externalDocs:
    # description: "Find out more"
    # url: "http://swagger.io"

- name: "profile"
  description: "Все, что связано с профилями"

# - name: "user"
#   description: "Operations about user"

#   externalDocs:
#     description: "Find out more about our store"
#     url: "http://swagger.io"

schemes:
# - "https"
- "http"

paths:
  /events:
    get:
      tags:
      - "events"
      summary: "Получить список ближайших мероприятий"
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"

  /events/[slug]:
    get:
      tags:
      - "events"
      summary: "Получить информацию о мероприятии"
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"

  /events/popular:
    get:
      tags:
      - "events"
      summary: "Получить список популярных событий"
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"

  /events/search:
    get:
      tags:
      - "events"
      summary: "Установление ws соединения для интерактивного поиска"
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"


  /events/search/[pattern]:
    get:
      tags:
      - "events"
      summary: "Получения событий подходящих под паттерн поиска"
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"

  /profile/mypage:
    get:
      tags:
      - "profile"
      summary: ""
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"


  /profile/mypage/wishes:
    get:
      tags:
      - "profile"
      summary: "Список моих пожеланий"
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"

    post:
      tags:
      - "profile"
      summary: "Добавить событие в список желаний"
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"

    delete:
      tags:
      - "profile"
      summary: "Убрать событие из списка желаний"
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"

  /profile/mypage/intentions:
    get:
      tags:
      - "profile"
      summary: "Список того, что я хочу подарить"
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"

    post:
      tags:
      - "profile"
      summary: "Добавить намерение подарить подарок"
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"

    delete:
      tags:
      - "profile"
      summary: "Отказаться дарить подарок"
      description: ""
      # operationId: "addPet"
      consumes: 
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"

  /profile/[id_or_name]/wishes:
    get:
      tags:
      - "profile"
      summary: "Список поделаний пользователя"
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"

  /profile/[id_or_name]/intentions:
    get:
      tags:
      - "profile"
      summary: "Список того, что мы хотим подарить пользователю"
      description: ""
      # operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - in: "body"
      #   name: "body"
      #   description: "Pet object that needs to be added to the store"
      #   required: true
      #   schema:
      #     $ref: "#/definitions/Pet"
      responses:
      #   405:
      #     description: "Invalid input"
      # security:
      # - petstore_auth:
      #   - "write:pets"
      #   - "read:pets"
 

securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

definitions:
  Event:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"

      quantity:
        type: "integer"
        format: "int32"

      shipDate:
        type: "string"
        format: "date-time"

      status:
        type: "string"
        description: "Order Status"
        enum:
        - "placed"
        - "approved"
        - "delivered"
        
      complete:
        type: "boolean"
        default: false
    xml:
      name: "Order"

  Instance:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Category"

  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Category"