swagger: "2.0"
info:
  description: "Это документация к API сервиса [service_name]"
  version: "1.0.0"
  title: "[service_name]"
  # termsOfService: "http://swagger.io/terms/"
  # contact:
  #   email: "apiteam@swagger.io"
  # license:
  #   name: "Apache 2.0"
  #   url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: "petstore.swagger.io"
# basePath: "/v2"
tags:
- name: "products"
  description: "Все, что связано с событиями"
  externalDocs:
    # description: "Find out more"
    # url: "http://swagger.io"

- name: "profile"
  description: "Все, что связано с профилями"

# - name: "notifications"
#   description: "Все, что связано с push уведомелниями"

- name: "auth"
  description: "Все, что связано с авторизацией"

schemes:
# - "https"
- "http"

paths:
  # /notifications:
  #   get:
  #     tags:
  #       - "notifications"
  #     summary: "Установление ws соединения, для получения уведомлений"
  #     consumes:
  #     - "application/json"
  #     produces:
  #     - "application/json"
  #     parameters:
  #     responses:
  #       101:
  #         description: "Успешно установлено ws соединение"
      

  /auth:
    get:
      tags:
      - "auth"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: "id"
          description: ""
          required: true
          type: "string"
      responses:
        200:
          description: "Успешно авторизовались"

    delete:
      tags:
      - "auth"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      responses:
        200:
          description: "Успешно разлогинились"



  /products:
    get:
      tags:
      - "products"
      summary: "Получить список новых товаров"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"

  /products/[slug]:
    get:
      tags:
      - "products"
      summary: "Получить информацию о товаре"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      responses:
        200:
          description: ""
          schema:
            item:
              $ref: "#/definitions/Product"

  /products/search/[pattern]:
    get:
      tags:
      - "products"
      summary: "Получения товаров подходящих под паттерн поиска"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"


  /profile/mypage:
    get:
      tags:
      - "profile"
      summary: ""
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      responses:
        200:
          description: ""
          schema:
            item:
              $ref: "#/definitions/Profile"


  /profile/mypage/wishes:
    get:
      tags:
      - "profile"
      summary: "Список моих пожеланий"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ExtendedWish"

    post:
      tags:
      - "profile"
      summary: "Добавить товар в список желаний"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "product_id"
        description: ""
        required: true
        type: "string"

      responses:
        201:
          description: ""

    delete:
      tags:
      - "profile"
      summary: "Убрать товар из списка желаний"
      description: ""

      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "product_id"
        description: ""
        required: true
        type: "string"

      responses:
        200:
          description: ""


  /profile/mypage/intentions:
    get:
      tags:
      - "profile"
      summary: "Список того, что я хочу подарить"
      description: ""

      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ExtendedIntention"

    post:
      tags:
      - "profile"
      summary: "Добавить намерение подарить товар"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "product_id"
        description: ""
        required: true
        type: "string"

      - name: "dest_id"
        description: ""
        required: true
        type: "string"

      responses:
        201:
          description: ""

    delete:
      tags:
      - "profile"
      summary: "Отказаться дарить товар"
      description: ""
      consumes: 
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "product_id"
        description: ""
        required: true
        type: "string"

      - name: "dest_id"
        description: ""
        required: true
        type: "string"

      responses:
        200:
          description: ""


  /profile/[dest_id]/wishes:
    get:
      tags:
      - "profile"
      summary: "Список пожеланий пользователя"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ExtendedWish"

  /profile/[dest_id]/intentions:
    get:
      tags:
      - "profile"
      summary: "Список того, что мы хотим подарить пользователю"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ExtendedIntention"

definitions:
  Product:
    type: "object"
    properties:
      _id:
        type: "string"

      product_name:
        type: "string"

      discription:
        type: "string"

      price:
        type: "float"
        format: "float32"
        
      img_url:
        type: "string"
        format: "URL"

      product_url:
        type: "string"
        format: "URL"

  Profile:
    type: "object"
    properties:
      _id:
        type: "string"

      uid:
        type: "integer"
        format: "int64"

      first_name:
        type: "string"

      last_name:
        type: "string"

      photo_url:
        type: "string"
        format: "URL"

      wishes:
        type: "array"
        format: User

      intentions:
        type: "array"
        format: User

  Wish:
    type: "object"
    properties:
      p_id:
        type: "string"

      reserved:
        type: "bool"

      sponsor_id:
        type: "string"

  Intention:
    type: "object"
    properties:
      product_id:
        type: "string"

      dest_id:
        type: "string"

  ExtendedWish:
    type: "object"
    properties:
      product_id:
        type: "string"

      reserved:
        type: "bool"

      sponsor_id:
        type: "string"

      _id:
        type: "string"

      product_name:
        type: "string"

      discription:
        type: "string"

      price:
        type: "float"
        format: "float32"
        
      img_url:
        type: "string"
        format: "URL"

      product_url:
        type: "string"
        format: "URL"

  ExtendedIntention:
    type: "object"
    properties:
      product_id:
        type: "string"

      dest_id:
        type: "string"

      _id:
        type: "string"

      product_name:
        type: "string"

      discription:
        type: "string"

      price:
        type: "float"
        format: "float32"
        
      img_url:
        type: "string"
        format: "URL"

      product_url:
        type: "string"
        format: "URL"
