swagger: "2.0"
info:
  description: "Это документация к API сервиса [service_name]"
  version: "1.0.0"
  title: "[service_name]"

tags:
- name: "products"
  description: "Все, что связано с событиями"

- name: "profile"
  description: "Все, что связано с профилями"

- name: "auth"
  description: "Все, что связано с авторизацией"

schemes:
- "https"
- "http"

paths:
  /auth:
    post:
      tags:
      - "auth"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/URL"
        
      responses:
        200:
          description: "Успешно авторизовались"
        401:
          description: "Невалидные данные авторизации"

    delete:
      tags:
      - "auth"
      responses:
        200:
          description: "Успешно разлогинились"



  /products:
    get:
      tags:
      - "products"
      summary: "Получить список новых товаров"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"

  /products/list:
    get:
      tags:
      - "products"
      summary: "Получить список новых товаров"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "start"
        in: "query"
        required: true
        type: "integer"
        format: "int64"
        
      - name: "limit"
        in: "query"
        required: true
        type: "integer"
        format: "int64"
        
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ProductsPagination"

        400:
          description: "невалидные параметры"

  /products/[slug]:
    get:
      tags:
      - "products"
      summary: "Получить информацию о товаре"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "slug"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "показать данные товара"
          schema:
            $ref: "#/definitions/Product"
        400:
          description: "некорректный запрос"
        404:
          description: "такого товара нет"

  /products/search:
    get:
      tags:
      - "products"
      summary: "Получения товаров подходящих под паттерн поиска"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "pattern"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/LiteProduct"

  /products/search/result:
    get:
      tags:
      - "products"
      summary: "Получения товаров подходящих под паттерн поиска (полная информация)"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "pattern"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"


  /profile/mypage:
    get:
      tags:
      - "profile"
      summary: "информация обо мне"
      description: "Получение информации пользователя"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Profile"


  /profile/mypage/wishes:
    get:
      tags:
      - "profile"
      summary: "Список моих пожеланий"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ExtendedMyWish"

    post:
      tags:
      - "profile"
      summary: "Добавить товар в список желаний"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/ProductId"
        
      responses:
        201:
          description: "Пожелание успешно добавлено"
        400:
          description: "Некорректные данные"
        404:
          description: "Такого продукта нет"

    delete:
      tags:
      - "profile"
      summary: "Убрать товар из списка желаний"
      description: ""

      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/ProductId"

      responses:
        200:
          description: ""


  /profile/mypage/intentions:
    get:
      tags:
      - "profile"
      summary: "Список того, что я хочу подарить"
      produces:
      - "application/json"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ExtendedIntention"

    post:
      tags:
      - "profile"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Intention"

      responses:
        201:
          description: ""

    delete:
      tags:
      - "profile"
      summary: "Отказаться дарить товар"
      consumes: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Intention"

      responses:
        200:
          description: ""


  /profile/[dest_id]/wishes:
    get:
      tags:
      - "profile"
      summary: "Список пожеланий пользователя, с пометками наших обещаний"
      produces:
      - "application/json"
      parameters:
      - name: "dest_id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ExtendedWish"
              

  /profile/[dest_id]/intentions:
    get:
      tags:
      - "profile"
      summary: "Список того, что мы хотим подарить пользователю"
      produces:
      - "application/json"
      parameters:
      - name: "dest_id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ExtendedIntention"

definitions:
  LiteProduct:
    type: "object"
    properties:
      _id:
        type: "string"

      product_name:
        type: "string"


  Product:
    type: "object"
    properties:
      _id:
        type: "string"

      product_name:
        type: "string"

      discription:
        type: "string"

      price:
        type: "integer"
        format: "int64"
        
      img_url:
        type: "string"
        format: "URL"

      product_url:
        type: "string"
        format: "URL"

  Profile:
    type: "object"
    properties:
      _id:
        type: "string"

      uid:
        type: "integer"
        format: "int64"

      first_name:
        type: "string"

      last_name:
        type: "string"

      photo_url:
        type: "string"
        format: "URL"

      wishes:
        type: "array"
        items:
          $ref: "#/definitions/Wish"

      intentions:
        type: "array"
        items:
          $ref: "#/definitions/Intention"

  Wish:
    type: "object"
    properties:
      p_id:
        type: "string"

      reserved:
        type: "boolean"

      sponsor_id:
        type: "string"

  Intention:
    type: "object"
    properties:
      product_id:
        type: "string"

      dest_id:
        type: "string"

  ExtendedWish:
    type: "object"
    properties:
      product_id:
        type: "string"

      reserved:
        type: "boolean"

      reserved_by_me:
        type: "boolean"

      _id:
        type: "string"

      product_name:
        type: "string"

      discription:
        type: "string"

      price:
        type: "number"
        format: "float32"
        
      img_url:
        type: "string"
        format: "URL"

      product_url:
        type: "string"
        format: "URL"


  ExtendedMyWish:
    type: "object"
    properties:
      product_id:
        type: "string"

      reserved:
        type: "boolean"

      _id:
        type: "string"

      product_name:
        type: "string"

      discription:
        type: "string"

      price:
        type: "number"
        format: "float32"
        
      img_url:
        type: "string"
        format: "URL"

      product_url:
        type: "string"
        format: "URL"
        

  ExtendedIntention:
    type: "object"
    properties:
      product_id:
        type: "string"

      dest_id:
        type: "string"

      _id:
        type: "string"

      product_name:
        type: "string"

      discription:
        type: "string"

      price:
        type: "number"
        format: "float32"
        
      img_url:
        type: "string"
        format: "URL"

      product_url:
        type: "string"
        format: "URL"
        
  ProductId:
    type: "object"
    properties:
      product_id:
        type: "string"

  URL:
    type: "object"
    properties:
      url:
        type: "string"

  ProductsPagination:
    type: "object"
    properties:
      total:
        type: "integer"
        format: "int64"

      products:
        type: "array"
        items:
          $ref: "#/definitions/Product"
